import { GetPaymentsResponse } from "./getPayments.types";

export const getPaymentsFixture: GetPaymentsResponse = {
  total_amount_left_to_pay: 40750,
  payments: [
    {
      id: "payment_121IopV7OU4kX5pMradVJfGAQzSJz7MGy2",
      created: 1751527297,
      state: "in_progress",
      installments_count: 4,
      merchant_display_name: "France_merchant",
      purchase_amount: 21000,
      payment_plan: [
        {
          id: "installment_121IopV7jNAHBV9kfHX66XiKbH88Z7K6Vh",
          purchase_amount: 5250,
          original_purchase_amount: 5250,
          due_date: 1751527297,
          original_due_date: null,
          date_paid: 1751527335,
          state: "paid",
          customer_fee: 378,
          customer_interest: 0,
          customer_can_postpone_until: null,
        },
        {
          id: "installment_121IopV5UspdWks53KZ1P5zTRRKG51sP9m",
          purchase_amount: 5250,
          original_purchase_amount: 5250,
          due_date: 1754205697,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0,
          customer_interest: 0,
          customer_can_postpone_until: "2025-09-03",
        },
        {
          id: "installment_121IopV6yEGwrRoMhkooKdJZONFD36bgPX",
          purchase_amount: 5250,
          original_purchase_amount: 5250,
          due_date: 1756884097,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0,
          customer_interest: 0,
          customer_can_postpone_until: "2025-10-03",
        },
        {
          id: "installment_121IopV5S0nF0Gc4IqzCSxfy1xBsG6B1tL",
          purchase_amount: 5250,
          original_purchase_amount: 5250,
          due_date: 1759476097,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0,
          customer_interest: 0,
          customer_can_postpone_until: "2025-11-03",
        },
      ],
      logo_url: null,
    },
    {
      id: "payment_121FwSk1IpNiGOXBhhbz17OUoERYj1Uwsz",
      created: 1750841654,
      state: "in_progress",
      installments_count: 4,
      merchant_display_name: "France_merchant",
      purchase_amount: 50000,
      payment_plan: [
        {
          id: "installment_121FwSn1rq3nQo1VFFnlaapwiSjbt2qBmV",
          purchase_amount: 12500,
          original_purchase_amount: 12500,
          due_date: 1750841657,
          original_due_date: null,
          date_paid: 1750841694,
          state: "paid",
          customer_fee: 900,
          customer_interest: 0,
          customer_can_postpone_until: null,
        },
        {
          id: "installment_121FwSn2IOGFIaQ6sQjjjkfkFpO6D5GsLD",
          purchase_amount: 12500,
          original_purchase_amount: 12500,
          due_date: 1753433657,
          original_due_date: null,
          date_paid: 1751287110,
          state: "paid",
          customer_fee: 0,
          customer_interest: 0,
          customer_can_postpone_until: null,
        },
        {
          id: "installment_121FwSn2ZIOco7uZ8124buNt3OE8h3lslW",
          purchase_amount: 12500,
          original_purchase_amount: 12500,
          due_date: 1756112057,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0,
          customer_interest: 0,
          customer_can_postpone_until: "2025-09-25",
        },
        {
          id: "installment_121FwSn4T1Ua42v2fLsUPwwJE08kc1dYnk",
          purchase_amount: 12500,
          original_purchase_amount: 12500,
          due_date: 1758790457,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0,
          customer_interest: 0,
          customer_can_postpone_until: "2025-10-26",
        },
      ],
      logo_url: null,
    },
  ],
};
