import {
  Amount,
  DayString,
  Timestamp,
} from "../../shared/domain/payment.types";
import { GetPaymentsResponse } from "./getPayments.types";

export const getPaymentsFixture: GetPaymentsResponse = {
  total_amount_left_to_pay: 40750 as Amount,
  payments: [
    {
      id: "payment_121IopV7OU4kX5pMradVJfGAQzSJz7MGy2",
      created: 1751527297 as Timestamp,
      state: "in_progress",
      installments_count: 4,
      merchant_display_name: "France_merchant",
      purchase_amount: 21000 as Amount,
      payment_plan: [
        {
          id: "installment_121IopV7jNAHBV9kfHX66XiKbH88Z7K6Vh",
          purchase_amount: 5250 as Amount,
          original_purchase_amount: 5250 as Amount,
          due_date: 1751527297 as Timestamp,
          original_due_date: null,
          date_paid: 1751527335 as Timestamp,
          state: "paid",
          customer_fee: 378 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: null,
        },
        {
          id: "installment_121IopV5UspdWks53KZ1P5zTRRKG51sP9m",
          purchase_amount: 5250 as Amount,
          original_purchase_amount: 5250 as Amount,
          due_date: 1754205697 as Timestamp,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: "2025-09-03" as DayString,
        },
        {
          id: "installment_121IopV6yEGwrRoMhkooKdJZONFD36bgPX",
          purchase_amount: 5250 as Amount,
          original_purchase_amount: 5250 as Amount,
          due_date: 1756884097 as Timestamp,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: "2025-10-03" as DayString,
        },
        {
          id: "installment_121IopV5S0nF0Gc4IqzCSxfy1xBsG6B1tL",
          purchase_amount: 5250 as Amount,
          original_purchase_amount: 5250 as Amount,
          due_date: 1759476097 as Timestamp,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: "2025-11-03" as DayString,
        },
      ],
      logo_url: null,
    },
    {
      id: "payment_121FwSk1IpNiGOXBhhbz17OUoERYj1Uwsz",
      created: 1750841654 as Timestamp,
      state: "in_progress",
      installments_count: 4,
      merchant_display_name: "France_merchant",
      purchase_amount: 50000 as Amount,
      payment_plan: [
        {
          id: "installment_121FwSn1rq3nQo1VFFnlaapwiSjbt2qBmV",
          purchase_amount: 12500 as Amount,
          original_purchase_amount: 12500 as Amount,
          due_date: 1750841657 as Timestamp,
          original_due_date: null,
          date_paid: 1750841694 as Timestamp,
          state: "paid",
          customer_fee: 900 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: null,
        },
        {
          id: "installment_121FwSn2IOGFIaQ6sQjjjkfkFpO6D5GsLD",
          purchase_amount: 12500 as Amount,
          original_purchase_amount: 12500 as Amount,
          due_date: 1753433657 as Timestamp,
          original_due_date: null,
          date_paid: 1751287110 as Timestamp,
          state: "paid",
          customer_fee: 0 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: null,
        },
        {
          id: "installment_121FwSn2ZIOco7uZ8124buNt3OE8h3lslW",
          purchase_amount: 12500 as Amount,
          original_purchase_amount: 12500 as Amount,
          due_date: 1756112057 as Timestamp,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: "2025-09-25" as DayString,
        },
        {
          id: "installment_121FwSn4T1Ua42v2fLsUPwwJE08kc1dYnk",
          purchase_amount: 12500 as Amount,
          original_purchase_amount: 12500 as Amount,
          due_date: 1758790457 as Timestamp,
          original_due_date: null,
          date_paid: null,
          state: "pending",
          customer_fee: 0 as Amount,
          customer_interest: 0 as Amount,
          customer_can_postpone_until: "2025-10-26" as DayString,
        },
      ],
      logo_url: null,
    },
  ],
};
