export const primitives = {
  blue: {
    "50": "#eef5ffff",
    "100": "#dae9ffff",
    "200": "#bdd9ffff",
    "300": "#90c2ffff",
    "400": "#539bffff",
    "500": "#357bfcff",
    "600": "#1f5bf1ff",
    "700": "#1745deff",
    "800": "#1939b4ff",
    "900": "#1a358eff",
    "950": "#152256ff",
  },
  green: {
    "50": "#f1fcf5ff",
    "100": "#defae9ff",
    "200": "#bef4d4ff",
    "300": "#8ce9b3ff",
    "400": "#52d689ff",
    "500": "#2fcc71ff",
    "600": "#1e9b53ff",
    "700": "#1b7a44ff",
    "800": "#1a6139ff",
    "900": "#184f31ff",
    "950": "#072c18ff",
  },
  grey: {
    "0": "#ffffffff",
    "50": "#f6f6f6ff",
    "100": "#e7e7e7ff",
    "200": "#d1d1d1ff",
    "300": "#b0b0b0ff",
    "400": "#888888ff",
    "500": "#6d6d6dff",
    "600": "#575757ff",
    "700": "#4f4f4fff",
    "800": "#454545ff",
    "900": "#3d3d3dff",
    "950": "#262626ff",
    "1000": "#000000ff",
  },
  purple: {
    "50": "#f4f1ffff",
    "100": "#ebe6ffff",
    "200": "#dad0ffff",
    "300": "#bfabffff",
    "400": "#a17bffff",
    "500": "#8546ffff",
    "600": "#7920ffff",
    "700": "#6e13f3ff",
    "800": "#590bccff",
    "900": "#4b0ca6ff",
    "950": "#2c0471ff",
  },
  red: {
    "50": "#fef2f2ff",
    "100": "#ffe1e1ff",
    "200": "#ffc8c8ff",
    "300": "#ffa2a2ff",
    "400": "#fd6565ff",
    "500": "#f53e3eff",
    "600": "#e31f1fff",
    "700": "#bf1616ff",
    "800": "#9e1616ff",
    "900": "#831919ff",
    "950": "#470808ff",
  },
  yellow: {
    "50": "#fffbebff",
    "100": "#fff4c6ff",
    "200": "#fee475ff",
    "300": "#fed64bff",
    "400": "#fdc222ff",
    "500": "#f7a109ff",
    "600": "#db7904ff",
    "700": "#b65507ff",
    "800": "#93410dff",
    "900": "#79360eff",
    "950": "#461b02ff",
  },
} as const;

export const foundation = {
  colors: {
    primary: {
      lowest: primitives["blue"]["50"],
      lower: primitives["blue"]["100"],
      low: primitives["blue"]["300"],
      medium: primitives["blue"]["500"],
      high: primitives["blue"]["700"],
      higher: primitives["blue"]["900"],
      highest: primitives["blue"]["950"],
    },
    secondary: {
      lowest: primitives["purple"]["50"],
      lower: primitives["purple"]["100"],
      low: primitives["purple"]["300"],
      medium: primitives["purple"]["500"],
      high: primitives["purple"]["700"],
      higher: primitives["purple"]["900"],
      highest: primitives["purple"]["950"],
    },
    neutral: {
      lowest: primitives["grey"]["50"],
      lower: primitives["grey"]["100"],
      low: primitives["grey"]["300"],
      medium: primitives["grey"]["500"],
      high: primitives["grey"]["700"],
      higher: primitives["grey"]["900"],
      highest: primitives["grey"]["950"],
      white: primitives["grey"]["0"],
      black: primitives["grey"]["1000"],
    },
    success: {
      lowest: primitives["green"]["50"],
      lower: primitives["green"]["100"],
      low: primitives["green"]["300"],
      medium: primitives["green"]["500"],
      high: primitives["green"]["700"],
      higher: primitives["green"]["900"],
      highest: primitives["green"]["950"],
    },
    warning: {
      lowest: primitives["yellow"]["50"],
      lower: primitives["yellow"]["100"],
      low: primitives["yellow"]["300"],
      medium: primitives["yellow"]["500"],
      high: primitives["yellow"]["700"],
      higher: primitives["yellow"]["900"],
      highest: primitives["yellow"]["950"],
    },
    error: {
      lowest: primitives["red"]["50"],
      lower: primitives["red"]["100"],
      low: primitives["red"]["300"],
      medium: primitives["red"]["500"],
      high: primitives["red"]["700"],
      higher: primitives["red"]["900"],
      highest: primitives["red"]["950"],
    },
    text: {
      lowest: primitives["grey"]["50"],
      lower: primitives["grey"]["100"],
      low: primitives["grey"]["300"],
      medium: primitives["grey"]["500"],
      high: primitives["grey"]["700"],
      higher: primitives["grey"]["900"],
      highest: primitives["grey"]["950"],
    },
    surface: {
      lowest: primitives["grey"]["50"],
      lower: primitives["grey"]["100"],
      low: primitives["grey"]["300"],
      medium: primitives["grey"]["500"],
      high: primitives["grey"]["700"],
      higher: primitives["grey"]["900"],
      highest: primitives["grey"]["950"],
      white: primitives["grey"]["0"],
      black: primitives["grey"]["1000"],
    },
  },
  sizes: {
    none: 0,
    full: 999,
    "size-0125": 1,
    "size-01875": 1.5,
    "size-025": 2,
    "size-0375": 3,
    "size-050": 4,
    "size-3000": 240,
    "size-2000": 160,
    "size-1900": 152,
    "size-1800": 144,
    "size-075": 6,
    "size-100": 8,
    "size-125": 10,
    "size-150": 12,
    "size-175": 14,
    "size-1700": 136,
    "size-1500": 120,
    "size-1600": 128,
    "size-1400": 112,
    "size-1300": 104,
    "size-1200": 96,
    "size-200": 16,
    "size-250": 20,
    "size-300": 24,
    "size-400": 32,
    "size-500": 40,
    "size-1100": 88,
    "size-1000": 80,
    "size-900": 72,
    "size-800": 64,
    "size-700": 56,
    "size-600": 48,
  },
} as const;

export const components = {
  button: {
    level: {
      primary: {
        disabled: {
          "background-color": foundation["colors"]["neutral"]["low"],
          "content-color": foundation["colors"]["neutral"]["higher"],
        },
        "content-color": foundation["colors"]["neutral"]["lowest"],
        "background-color": foundation["colors"]["primary"]["highest"],
        hover: {
          "background-color": foundation["colors"]["primary"]["higher"],
        },
        active: {
          "background-color": foundation["colors"]["primary"]["higher"],
        },
        "border-size": foundation["sizes"]["none"],
      },
      secondary: {
        disabled: {
          "background-color": foundation["colors"]["neutral"]["low"],
          "content-color": foundation["colors"]["neutral"]["higher"],
          "border-color": foundation["colors"]["neutral"]["low"],
        },
        "content-color": foundation["colors"]["primary"]["highest"],
        "border-color": foundation["colors"]["primary"]["highest"],
        hover: {
          "background-color": foundation["colors"]["primary"]["lower"],
          "border-color": foundation["colors"]["primary"]["highest"],
          "content-color": foundation["colors"]["primary"]["highest"],
        },
        active: {
          "background-color": foundation["colors"]["primary"]["highest"],
          "content-color": foundation["colors"]["neutral"]["lowest"],
        },
        "background-color": foundation["colors"]["neutral"]["white"],
        "border-size": foundation["sizes"]["size-025"],
      },
    },
    "corner-radius": foundation["sizes"]["size-100"],
    gap: foundation["sizes"]["size-100"],
    "horizontal-padding": foundation["sizes"]["size-200"],
    size: {
      XS: {
        "vertical-padding": foundation["sizes"]["size-050"],
        height: foundation["sizes"]["size-400"],
        "icon-size": foundation["sizes"]["size-200"],
      },
      S: {
        height: foundation["sizes"]["size-500"],
        "icon-size": foundation["sizes"]["size-300"],
        "vertical-padding": foundation["sizes"]["size-100"],
      },
      M: {
        height: foundation["sizes"]["size-600"],
        "icon-size": foundation["sizes"]["size-300"],
        "vertical-padding": foundation["sizes"]["size-150"],
      },
      L: {
        height: foundation["sizes"]["size-700"],
        "icon-size": foundation["sizes"]["size-300"],
        "vertical-padding": foundation["sizes"]["size-200"],
      },
    },
    "focused-corner-radius": foundation["sizes"]["size-125"],
  },
  "focused-color": foundation["colors"]["neutral"]["highest"],
  switch: {
    state: {
      default: {
        selected: {
          "background-color": foundation["colors"]["primary"]["high"],
        },
        unselected: {
          "background-color": foundation["colors"]["neutral"]["medium"],
        },
      },
      hover: {
        selected: {
          "background-color": foundation["colors"]["primary"]["higher"],
        },
        unselected: {
          "background-color": foundation["colors"]["neutral"]["high"],
        },
      },
      active: {
        selected: {
          "background-color": foundation["colors"]["primary"]["higher"],
        },
        unselected: {
          "background-color": foundation["colors"]["neutral"]["high"],
        },
      },
      focus: {
        selected: {
          "background-color": foundation["colors"]["primary"]["high"],
        },
        unselected: {
          "background-color": foundation["colors"]["neutral"]["medium"],
        },
      },
      disabled: {
        selected: {
          "background-color": foundation["colors"]["neutral"]["low"],
          "content-color": foundation["colors"]["neutral"]["medium"],
        },
        unselected: {
          "background-color": foundation["colors"]["neutral"]["low"],
          "content-color": foundation["colors"]["neutral"]["medium"],
        },
      },
    },
    "content-color": foundation["colors"]["neutral"]["lowest"],
    size: {
      "M-height": foundation["sizes"]["size-200"],
      "M-width": foundation["sizes"]["size-400"],
      "L-height": foundation["sizes"]["size-300"],
      "L-width": foundation["sizes"]["size-600"],
      "M-content-size": foundation["sizes"]["size-150"],
      "L-content-size": foundation["sizes"]["size-250"],
      "M-icon-size": foundation["sizes"]["size-125"],
      "L-icon-size": foundation["sizes"]["size-200"],
    },
    "corner-radius": foundation["sizes"]["full"],
    "focused-corner-radius": foundation["sizes"]["full"],
    "icon-ON-color": foundation["colors"]["primary"]["highest"],
    "icon-OFF-color": foundation["colors"]["neutral"]["low"],
  },
  "input-content": {
    option: {
      empty: { "text-color": foundation["colors"]["neutral"]["medium"] },
      filled: { "text-color": foundation["colors"]["primary"]["highest"] },
    },
    "icon-color": foundation["colors"]["primary"]["highest"],
    state: {
      disabled: { "content-color": foundation["colors"]["neutral"]["high"] },
      active: { "icon-color": foundation["colors"]["primary"]["higher"] },
    },
    "info-color": foundation["colors"]["primary"]["high"],
    "min-height": foundation["sizes"]["size-300"],
    gap: foundation["sizes"]["size-100"],
  },
  input: {
    state: {
      hover: {
        "border-color": foundation["colors"]["neutral"]["medium"],
        success: { test: "#ffffffff" },
        error: { test: "#ffffffff" },
      },
      active: {
        "border-color": foundation["colors"]["primary"]["highest"],
        success: { test: "#ffffffff" },
        error: { test: "#ffffffff" },
      },
      disabled: {
        "background-color": foundation["colors"]["neutral"]["lower"],
        "border-color": foundation["colors"]["neutral"]["lower"],
      },
      "read-only": {
        "background-color": foundation["colors"]["primary"]["lowest"],
        "border-color": foundation["colors"]["primary"]["lowest"],
      },
      default: {
        error: {
          "background-color": foundation["colors"]["error"]["lowest"],
          "border-color": foundation["colors"]["error"]["medium"],
          "icon-color": foundation["colors"]["error"]["medium"],
        },
        success: { "border-color": foundation["colors"]["success"]["medium"] },
      },
    },
    "background-color": foundation["colors"]["neutral"]["white"],
    "border-color": foundation["colors"]["neutral"]["low"],
    "content-color": foundation["colors"]["primary"]["highest"],
    "corner-radius": foundation["sizes"]["size-075"],
    border: foundation["sizes"]["size-0125"],
    gap: foundation["sizes"]["size-100"],
    "horizontal-padding": foundation["sizes"]["size-100"],
    "vertical-padding": foundation["sizes"]["size-100"],
    "focused-corner-radius": foundation["sizes"]["size-100"],
    "text-area-vertical-padding-top": foundation["sizes"]["size-175"],
    "text-area-vertical-padding-bottom": foundation["sizes"]["size-100"],
    "legend-default-color": foundation["colors"]["primary"]["highest"],
    "legend-error-color": foundation["colors"]["error"]["medium"],
    "legend-success-color": foundation["colors"]["success"]["medium"],
  },
  cursor: { "background-color": foundation["colors"]["primary"]["higher"] },
  "radio-button": {
    hover: {
      "chip-color": foundation["colors"]["primary"]["higher"],
      "text-color": foundation["colors"]["primary"]["higher"],
      "border-color": foundation["colors"]["primary"]["higher"],
    },
    disabled: {
      "chip-color": foundation["colors"]["neutral"]["low"],
      "text-color": foundation["colors"]["neutral"]["medium"],
      "border-color": foundation["colors"]["neutral"]["low"],
    },
    "chip-color": foundation["colors"]["primary"]["highest"],
    "text-color": foundation["colors"]["primary"]["highest"],
    "border-color": foundation["colors"]["primary"]["highest"],
    gap: foundation["sizes"]["size-100"],
    "container-size": foundation["sizes"]["size-250"],
    "chip-min-size": foundation["sizes"]["size-025"],
    "chip-max-size": foundation["sizes"]["size-100"],
    "container-border-width": foundation["sizes"]["size-025"],
    "focused-corner-radius": foundation["sizes"]["full"],
    "focused-size": foundation["sizes"]["size-300"],
    padding: foundation["sizes"]["size-025"],
  },
  checkbox: {
    hover: {
      "text-color": foundation["colors"]["primary"]["higher"],
      "border-color": foundation["colors"]["primary"]["higher"],
      "background-color": foundation["colors"]["primary"]["higher"],
    },
    "text-color": foundation["colors"]["primary"]["highest"],
    "border-color": foundation["colors"]["primary"]["highest"],
    disabled: {
      "text-color": foundation["colors"]["neutral"]["high"],
      "border-color": foundation["colors"]["neutral"]["low"],
      "icon-color": foundation["colors"]["neutral"]["higher"],
      "background-color": foundation["colors"]["neutral"]["low"],
    },
    "icon-color": foundation["colors"]["neutral"]["lowest"],
    "background-color": foundation["colors"]["primary"]["highest"],
    "container-size": foundation["sizes"]["size-250"],
    "container-corner-radius": foundation["sizes"]["size-050"],
    "container-border-width": foundation["sizes"]["size-01875"],
    "focused-corner-radius": foundation["sizes"]["size-075"],
    gap: foundation["sizes"]["size-100"],
    "focused-size": foundation["sizes"]["size-300"],
    padding: foundation["sizes"]["size-025"],
  },
  link: {
    "text-color": foundation["colors"]["primary"]["highest"],
    "underline-color": foundation["colors"]["secondary"]["medium"],
    "icon-color": foundation["colors"]["primary"]["highest"],
    hover: { "text-color": foundation["colors"]["primary"]["higher"] },
    active: { "text-color": foundation["colors"]["primary"]["high"] },
    "focused-corner-radius": foundation["sizes"]["size-050"],
    gap: foundation["sizes"]["size-100"],
    "horizontal-padding": foundation["sizes"]["size-025"],
    height: foundation["sizes"]["size-400"],
    "underline-height": foundation["sizes"]["size-025"],
    "underline-corner-radius": foundation["sizes"]["full"],
  },
  modal: {
    "background-color": foundation["colors"]["neutral"]["lowest"],
    "content-color": foundation["colors"]["primary"]["highest"],
    gap: foundation["sizes"]["size-300"],
    "horizontal-padding": foundation["sizes"]["size-300"],
    "vertical-padding": foundation["sizes"]["size-300"],
    "corner-radius": foundation["sizes"]["size-200"],
  },
  "button-icon": {
    level: {
      primary: {
        disabled: {
          "background-color": foundation["colors"]["neutral"]["low"],
          "content-color": foundation["colors"]["neutral"]["higher"],
        },
        "content-color": foundation["colors"]["neutral"]["lowest"],
        "background-color": foundation["colors"]["primary"]["highest"],
        hover: {
          "background-color": foundation["colors"]["primary"]["higher"],
        },
        active: {
          "background-color": foundation["colors"]["primary"]["highest"],
        },
      },
      secondary: {
        "content-color": foundation["colors"]["primary"]["highest"],
        "background-color": foundation["colors"]["primary"]["highest"],
        hover: { "background-color": foundation["colors"]["primary"]["lower"] },
        active: { "background-color": foundation["colors"]["primary"]["low"] },
        disabled: {
          "background-color": foundation["colors"]["neutral"]["low"],
          "content-color": foundation["colors"]["neutral"]["higher"],
        },
      },
    },
    size: {
      "width-S": foundation["sizes"]["size-500"],
      "height-S": foundation["sizes"]["size-500"],
      "height-XS": foundation["sizes"]["size-400"],
      "height-M": foundation["sizes"]["size-600"],
      "height-L": foundation["sizes"]["size-700"],
      "width-XS": foundation["sizes"]["size-400"],
      "width-M": foundation["sizes"]["size-600"],
      "width-L": foundation["sizes"]["size-700"],
    },
    "corner-radius": foundation["sizes"]["full"],
    "focused-corner-radius": foundation["sizes"]["full"],
  },
  pagination: { "content-color": foundation["colors"]["primary"]["highest"] },
  "pagination-item": {
    "content-color": foundation["colors"]["primary"]["highest"],
    "border-color": foundation["colors"]["primary"]["highest"],
    "background-color": foundation["colors"]["primary"]["lowest"],
    hover: { "background-color": foundation["colors"]["primary"]["lower"] },
    active: { "background-color": foundation["colors"]["primary"]["low"] },
    disabled: {
      "content-color": foundation["colors"]["neutral"]["higher"],
      "background-color": foundation["colors"]["neutral"]["low"],
    },
    width: foundation["sizes"]["size-500"],
    height: foundation["sizes"]["size-500"],
    "corner-radius": foundation["sizes"]["full"],
    "focused-corner-radius": foundation["sizes"]["full"],
    gap: foundation["sizes"]["size-100"],
    "horizontal-padding": foundation["sizes"]["size-100"],
    "vertical-padding": foundation["sizes"]["size-100"],
    "content-size": foundation["sizes"]["size-300"],
  },
  toast: {
    statut: {
      info: { "background-color": foundation["colors"]["primary"]["lower"] },
      success: { "background-color": foundation["colors"]["success"]["lower"] },
      warning: { "background-color": foundation["colors"]["warning"]["lower"] },
      error: { "background-color": foundation["colors"]["error"]["lower"] },
    },
    "content-color": foundation["colors"]["primary"]["highest"],
    gap: foundation["sizes"]["size-200"],
    "horizontal-padding": foundation["sizes"]["size-300"],
    "vertical-padding": foundation["sizes"]["size-300"],
    "corner-radius": foundation["sizes"]["size-100"],
    "gap-buttons": foundation["sizes"]["size-300"],
  },
  tag: {
    "content-color": foundation["colors"]["primary"]["highest"],
    level: {
      error: {
        "background-color": foundation["colors"]["error"]["lower"],
        hover: { "background-color": foundation["colors"]["error"]["low"] },
        "content-color": foundation["colors"]["error"]["higher"],
      },
      primary: {
        "background-color": foundation["colors"]["primary"]["lower"],
        hover: { "background-color": foundation["colors"]["primary"]["low"] },
      },
      success: {
        "background-color": foundation["colors"]["success"]["lower"],
        hover: { "background-color": foundation["colors"]["success"]["low"] },
        "content-color": foundation["colors"]["success"]["higher"],
      },
      warning: {
        "background-color": foundation["colors"]["warning"]["lower"],
        hover: { "background-color": foundation["colors"]["warning"]["low"] },
        "content-color": foundation["colors"]["warning"]["higher"],
      },
      secondary: {
        "background-color": foundation["colors"]["secondary"]["lower"],
        hover: { "background-color": foundation["colors"]["secondary"]["low"] },
      },
    },
    disabled: {
      "background-color": foundation["colors"]["neutral"]["lower"],
      "content-color": foundation["colors"]["neutral"]["high"],
    },
    gap: foundation["sizes"]["none"],
    "left-padding": foundation["sizes"]["size-050"],
    "vertical-padding": foundation["sizes"]["none"],
    "corner-radius": foundation["sizes"]["size-050"],
    "focused-corner-radius": foundation["sizes"]["size-075"],
    "close-icon-size": foundation["sizes"]["size-300"],
    "right-padding": foundation["sizes"]["size-050"],
    "label-left-padding": foundation["sizes"]["size-050"],
  },
  "focused-border": foundation["sizes"]["size-025"],
  "icon-size-M": foundation["sizes"]["size-300"],
  tooltip: {
    "background-color": foundation["colors"]["primary"]["highest"],
    "content-color": foundation["colors"]["neutral"]["lowest"],
    "corner-radius": foundation["sizes"]["size-050"],
    "image-corner-radius": foundation["sizes"]["size-025"],
    gap: foundation["sizes"]["size-200"],
    "horizontal-padding": foundation["sizes"]["size-175"],
    "vertical-padding": foundation["sizes"]["size-175"],
    "max-width": foundation["sizes"]["size-3000"],
    "image-max-height": foundation["sizes"]["size-1500"],
  },
  "breadcrumbs-item": {
    "content-color": foundation["colors"]["primary"]["highest"],
    hover: { "content-color": foundation["colors"]["primary"]["higher"] },
    active: { "content-color": foundation["colors"]["primary"]["high"] },
    disabled: { "content-color": foundation["colors"]["neutral"]["medium"] },
    height: foundation["sizes"]["size-200"],
    "icon-gap": foundation["sizes"]["size-050"],
    "item-gap": foundation["sizes"]["size-200"],
    "focused-corner-radius": foundation["sizes"]["size-050"],
  },
  "breadcrumbs-bar": { "item-gap": foundation["sizes"]["size-200"] },
  "table-item": {
    "text-color": foundation["colors"]["primary"]["highest"],
    "underline-color": foundation["colors"]["neutral"]["low"],
    active: { "underline-color": foundation["colors"]["primary"]["medium"] },
    hover: { "background-color": foundation["colors"]["neutral"]["lower"] },
  },
  "table-line": {
    "underline-color": foundation["colors"]["neutral"]["low"],
    hover: { "background-color": foundation["colors"]["neutral"]["lower"] },
    active: { "underline-color": foundation["colors"]["primary"]["medium"] },
  },
  accordion: {
    "border-color": foundation["colors"]["primary"]["highest"],
    hover: { "background-color": foundation["colors"]["primary"]["lower"] },
    active: { "border-color": foundation["colors"]["primary"]["medium"] },
    disabled: {
      "background-color": foundation["colors"]["neutral"]["low"],
      "content-color": foundation["colors"]["neutral"]["higher"],
    },
    "content-color": foundation["colors"]["primary"]["highest"],
    "border-size": foundation["sizes"]["size-025"],
    "corner-radius": foundation["sizes"]["size-100"],
    "horizontal-padding": foundation["sizes"]["size-300"],
    "vertical-padding": foundation["sizes"]["size-300"],
    gap: foundation["sizes"]["size-300"],
    "background-color": foundation["colors"]["neutral"]["lowest"],
    height: foundation["sizes"]["size-1000"],
    "header-min-height": foundation["sizes"]["size-400"],
  },
  "icon-size-S": foundation["sizes"]["size-200"],
  "icon-size-L": foundation["sizes"]["size-400"],
  "bottom-sheet": {
    "background-color": foundation["colors"]["neutral"]["lowest"],
    "content-color": foundation["colors"]["primary"]["highest"],
    gap: foundation["sizes"]["size-400"],
    "horizontal-padding": foundation["sizes"]["size-400"],
    "top-padding": foundation["sizes"]["size-500"],
    "corner-radius": foundation["sizes"]["size-200"],
    "bottom-padding": foundation["sizes"]["size-700"],
  },
  banner: {
    "content-color": foundation["colors"]["primary"]["highest"],
    gap: foundation["sizes"]["size-200"],
    statut: {
      warning: {
        "background-color": foundation["colors"]["warning"]["lower"],
        "border-color": foundation["colors"]["warning"]["lower"],
      },
      error: {
        "background-color": foundation["colors"]["error"]["lower"],
        "border-color": foundation["colors"]["error"]["lower"],
      },
      info: {
        "background-color": foundation["colors"]["primary"]["lower"],
        "border-color": foundation["colors"]["primary"]["lower"],
      },
      success: {
        "background-color": foundation["colors"]["success"]["lower"],
        "border-color": foundation["colors"]["success"]["lower"],
      },
    },
    "horizontal-padding": foundation["sizes"]["size-200"],
    "vertical-padding": foundation["sizes"]["size-200"],
    "corner-radius": foundation["sizes"]["size-100"],
    "border-size": foundation["sizes"]["none"],
  },
  "stepper-item": {
    inactive: {
      "background-color": foundation["colors"]["neutral"]["lower"],
      "content-color": foundation["colors"]["neutral"]["highest"],
    },
    "in-progress": {
      "background-color": foundation["colors"]["primary"]["medium"],
      "content-color": foundation["colors"]["neutral"]["lowest"],
    },
    completed: {
      "background-color": foundation["colors"]["success"]["lower"],
      "content-color": foundation["colors"]["success"]["higher"],
    },
    error: {
      "background-color": foundation["colors"]["error"]["lower"],
      "content-color": foundation["colors"]["error"]["higher"],
    },
    "step-size": foundation["sizes"]["size-300"],
  },
  stepper: {
    "title-color": foundation["colors"]["neutral"]["highest"],
    "description-color": foundation["colors"]["neutral"]["high"],
    "line-inactive-color": foundation["colors"]["neutral"]["lower"],
    "line-active-color": foundation["colors"]["primary"]["medium"],
  },
  tab: {
    "content-color": foundation["colors"]["neutral"]["high"],
    active: {
      "content-color": foundation["colors"]["primary"]["medium"],
      "underline-color": foundation["colors"]["primary"]["medium"],
    },
    "underline-color": foundation["colors"]["primary"]["lower"],
    height: foundation["sizes"]["size-500"],
    "horizontal-padding": foundation["sizes"]["size-100"],
    "top-padding": foundation["sizes"]["size-100"],
    "underline-height": foundation["sizes"]["size-0375"],
    "underline-corner-radius": foundation["sizes"]["full"],
    "focused-corner-radius": foundation["sizes"]["size-050"],
    gap: foundation["sizes"]["size-100"],
    "underline-width": foundation["sizes"]["size-0375"],
    "border-color": foundation["colors"]["neutral"]["low"],
  },
  "tabbar-item": {
    default: { "content-color": foundation["colors"]["neutral"]["medium"] },
    active: { "content-color": foundation["colors"]["neutral"]["highest"] },
    "icon-size": foundation["sizes"]["size-400"],
    gap: foundation["sizes"]["size-050"],
  },
  tabbar: {
    height: foundation["sizes"]["size-1000"],
    "background-color": foundation["colors"]["neutral"]["lowest"],
    "top-corner-radius": foundation["sizes"]["size-300"],
    "top-padding": foundation["sizes"]["size-075"],
  },
  avatar: {
    "content-color": foundation["colors"]["primary"]["highest"],
    "background-color": foundation["colors"]["primary"]["lower"],
    "notification-background-color": foundation["colors"]["error"]["medium"],
    "notification-content-color": foundation["colors"]["neutral"]["lowest"],
    "corner-radius": foundation["sizes"]["size-100"],
    width: foundation["sizes"]["size-500"],
    height: foundation["sizes"]["size-500"],
    "border-color": foundation["colors"]["neutral"]["lowest"],
    gap: foundation["sizes"]["size-100"],
  },
} as const;

export const typographie = {
  font: {
    family: { tagline: "vesterbro", title: "inter", text: "inter" },
    weight: {
      medium: "medium",
      regular: "regular",
      "semi-bold": "semibold",
      italic: "italic",
      bold: "bold",
      "extra-bold": "extrabold",
    },
    size: {
      "2xs": 10,
      xs: 12,
      sm: 14,
      md: 16,
      lg: 20,
      xl: 24,
      "2xl": 32,
      "3xl": 40,
      "4xl": 72,
    },
  },
} as const;
